### ISSUE TITLE
getting error from node app.js

### ISSUE THREAD

**Issue by lantos** [kevincobain2000/instagram-bot-api#1]
npm WARN deprecated node@0.0.0: To update or install node, go to http://nodejs.org/
npm WARN engine express@2.5.9: wanted: {"node":">= 0.4.1 < 0.7.0"} (current: {"node":"0.12.4","npm":"2.10.1"})

> contextify@0.1.14 install /Users/lantos/node_modules/app.js/node_modules/jsdom/node_modules/contextify
> node-gyp rebuild

gyp ERR! build error 
gyp ERR! stack Error: not found: make
gyp ERR! stack     at F (/usr/local/lib/node_modules/npm/node_modules/which/which.js:72:28)
gyp ERR! stack     at E (/usr/local/lib/node_modules/npm/node_modules/which/which.js:75:29)
gyp ERR! stack     at /usr/local/lib/node_modules/npm/node_modules/which/which.js:83:16
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:95:15)
gyp ERR! System Darwin 12.5.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
ERR! cwd /Users/lantos/node_modules/app.js/node_modules/jsdom/node_modules/contextify
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok 
npm ERR! Darwin 12.5.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "node" "app.js"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! contextify@0.1.14 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the contextify@0.1.14 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the contextify package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls contextify
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/lantos/npm-debug.log

**Comment by Naramsim** [comment]
try to update your node.
in Unix: 
`sudo npm cache clean -f &&
sudo npm install -g n &&
sudo n stable`

**Comment by kevincobain2000** [comment]
@Naramsim Thanks mate

**Comment by Khushboo88** [comment]
in windows git bash..?

**Comment by Khushboo88** [comment]
i got same error..
npm WARN package.json content-collection@0.0.1 No license field.

> bufferutil@1.2.1 install C:\NewSource\content-collection\node_modules\bufferutil
> node-gyp rebuild

C:\NewSource\content-collection\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (rebuild)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:103:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:64:11
gyp ERR! stack     at FSReqWrap.oncomplete (evalmachine.<anonymous>:95:15)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
gyp ERR! cwd C:\NewSource\content-collection\node_modules\bufferutil
gyp ERR! node -v v0.12.4
gyp ERR! node-gyp -v v1.0.3
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE
npm ERR! bufferutil@1.2.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the bufferutil package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls bufferutil
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\NewSource\content-collection\npm-debug.log

**Comment by Naramsim** [comment]
stack Error: Can't find Python executable "python", you can set the PYTHON env variable 
install python and add it to the path

**Comment by kevincobain2000** [comment]
Thanks @Naramsim
